spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: environment-service
          uri: lb://environment-service
          predicates:
            - Path=/environment-service/**
          filters:
            - RewritePath=/environment-service/(?<segment>.*), /${segment}

        - id: controle-service
          uri: lb://controle-service
          predicates:
            - Path=/controle-service/**
          filters:
            - RewritePath=/controle-service/(?<segment>.*), /${segment}

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
